name: dhadkan
description: "Dhadkan"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.20.0
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  flutter_charts: ^0.5.2
  fl_chart: ^0.69.2
  shared_preferences: ^2.2.3
  flutter_pdfview: ^1.3.2
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.1
  http: ^0.13.3
  web_socket_channel: ^2.4.0
  flutter_sound: ^9.23.1
  file_selector: ^1.0.3
  dio: ^5.6.0
  dropdown_search: ^5.0.6
  image_picker: ^1.1.2
  record: ^6.1.1

  http_parser: any
  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_flutter: ^1.1.0
  
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true # Explicitly set the icon name for Android
  ios: true
  image_path: "assets/Images/app_logo.png"
  adaptive_icon_background: "#FFFFFF" # White background for adaptive icons
  adaptive_icon_foreground: "assets/Images/app_logo.png"
  remove_alpha_ios: true # Remove transparency for iOS
  min_sdk_android: 21 # Match your minSdkVersion
flutter:
  uses-material-design: true
  assets:
    - assets/Images/patient.png
    - assets/Images/doctor.png
    - assets/Images/doctor2.png
    - assets/Images/logo.png
    - assets/Images/patient2.png
    - assets/Images/app_logo.png